version: '3.2'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod
    networks:
    - app

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - app

  car_app:
    build: "./car_app"
    volumes:
      - ./car_app/src:/home/src
      - ./car_app/out:/home/out
      - log-volume:/home/out
    depends_on:
      - mongo
    ports:
      - "5001:5001"
    env_file:
      - car_app/docker.properties.env
    networks:
      - app

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    env_file:
    - env.influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./car_app/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - log-volume:/var/log/car_app/

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - env.influxdb
    links:
      - influxdb

volumes:
  log-volume:
networks:
  app:
    driver: bridge