version: '3.2'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod
    networks:
    - app

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - app

  car_app:
    build: "./car_app"
    volumes:
      - ./car_app/src:/home/src
    depends_on:
      - mongo
    ports:
      - "5001:5001"
    env_file:
      - car_app/docker.properties.env
    networks:
      - app

networks:
  app:
    driver: bridge