version: '2'

services:

  feed:
    container_name: leader
    image: ${PROJECT_NAME}/leader
    build: ./leader
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - router
      - nanny
    stop_grace_period: 5s
    env_file:
      - feed_platform/docker.env

  worker:
    build: ./worker
    image: ${PROJECT_NAME}/worker
    volumes:
    - /var/run/docker.docker:/sock/var/run.sock
    depends_on:
    - nanny
    stop_grace_period: 5s
    env_file:
    - feed_platform/docker.env

  router:
    container_name: router
    build: ./routing
    image: ${PROJECT_NAME}/router
    ports:
    - "5002:5000"
    stop_grace_period: 5s
    env_file:
      - feed_platform/docker.env

  nanny:
    container_name: nanny
    build: ./nanny
    image: nanny
    volumes:
    - ./config:/home/config
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "5003:5000"
    environment:
      BROWSER_BASE_PORT: 4444
    stop_grace_period: 5s
    env_file:
      - feed_platform/docker.env

  ui-server:
    container_name: ui-server
    build: ./ui-server
    image: ${PROJECT_NAME}/ui-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5004:5000"
    env_file:
      - feed_platform/docker.env

  summarizer:
    container_name: summarizer
    build: ./summarizer
    image: ${PROJECT_NAME}/summarizer
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    stop_grace_period: 5s
    env_file:
    - feed_platform/docker.env

  mapper:
    container_name: mapper
    build: ./mapper
    image: ${PROJECT_NAME}/mapper
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    stop_grace_period: 5s
    env_file:
    - feed_platform/docker.env

  persistence:
    container_name: persistence
    build: ./persistence
    image: ${PROJECT_NAME}/persistence
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    stop_grace_period: 5s
    env_file:
      - feed_platform/docker.env
