version: '2'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  car-feed:
    image: car-feed
    container_name: car-feed
    build: "./car_app"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - log-volume:/home/out/
    depends_on:
      - mongo
    ports:
      - "5001:5001"
    env_file:
      - car_app/docker.properties.env

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "25826:25826/udp"
    env_file:
    - env.influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf

    depends_on:
      - influxdb
    volumes:
      - ./car_app/telegraf/patterns.conf:/etc/telegraf/patterns.conf:ro
      - ./car_app/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./car_app/telegraf/supervisord.conf:/etc/telegraf/supervisord.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - log-volume:/var/log/car_app:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - env.influxdb
    depends_on:
      - influxdb
    volumes:
      - ./car_app/grafana:/var/lib/grafana/

volumes:
  log-volume:
  patterns: