version: '3'

services:
  mongo-express:
    image: car-images/mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  mongo:
    image: car-images/mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod

  influxdb:
    image: car-images/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "25826:25826/udp"
    env_file:
      - env.influxdb

  grafana:
    image: car-app/grafana
    ports:
      - "3000:3000"
    env_file:
      - env.influxdb
