version: '3.2'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod

  car-feed:
    image: car-feed
    build: "../car_app"
    volumes:
      - ../car_app/src:/home/src
      - /car-browser:/home/car-browser # copy files to connect to aws docker daemon
      - log-volume:/home/out/
    ports:
      - "5001:5001"
    env_file:
      - task_configurations/docker.properties.env

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "25826:25826/udp"
    env_file:
    - task_configurations/env.influxdb


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ../car_app/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ../car_app/patterns.conf:/etc/telegraf/patterns.conf:ro
      - log-volume:/var/log/car_app/

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - task_configurations/env.influxdb
    links:
      - influxdb

volumes:
  log-volume:
