version: '3.2'

services:

  test_mongo:
    image: mongo
    restart: always
    ports:
    - "27000:27000"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod
    networks:
    - app

  test_car_app:
    build: "./"
    volumes:
      - ./src:/home/src
      - ./test:/home/test
      - /var/run/docker.sock:/var/run/docker.sock # mount the docker.sock to allow this container to control docker
    command:
      - ['python', 'unittest', '--start-directory', './src/test', '--pattern', 'test*.py']
    depends_on:
      - mongo
    env_file:
      - test.docker.env
    networks:
      - app
