version: 1
task_definition:
  task_execution_role:  ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 512
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
      - subnet-0f6e3276
      - subnet-49daf513
      - subnet-e7c4baac
      security_groups:
      -  sg-08d9b464377ab8cd2
      assign_public_ip: ENABLED